---
apiVersion: v1
kind: Service
metadata:
  annotations:
    qbec.io/component: app
  labels:
    qbec.io/application: demoapp
    qbec.io/environment: prod
  name: demoapp
spec:
  ports:
  - name: web
    nodePort: 30666
    port: 8282
    targetPort: 80
  selector:
    app: demoapp
  type: NodePort